package hearth
package typed

import hearth.data.Data

/** Macro implementation is in [[MethodsFixturesImpl]] */
final class MethodsSpec extends MacroSuite {

  group("trait typed.Methods") {

    group("methods: Method.methodsOf[A], returns preprocessed methods") {
      import MethodsFixtures.testMethodsExtraction

      test("for java.lang.Object") {
        def envDependentAnnotations(ann: String*): Data =
          if (LanguageVersion.byHearth.isScala2_13) Data.list(ann.map(Data(_))*)
          else Data.list() // Java annotations seem to be skipped on Scala 3 :/

        testMethodsExtraction[java.lang.Object]() <==> Data.map(
          // actual methods of java.lang.Object
          "clone()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> envDependentAnnotations(
              "new throws[CloneNotSupportedException](classOf[java.lang.CloneNotSupportedException])",
              "new native()"
            ),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(false),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          (if (LanguageVersion.byHearth.isScala2_13) "equals(Object)"
           else "equals(Any)") -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "finalize()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> envDependentAnnotations(
              "new throws[Throwable](classOf[java.lang.Throwable])",
              "new Deprecated(since = \"9\")"
            ),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(false),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          (if (LanguageVersion.byHearth.isScala2_13) "getClass()"
           else "getClass")
            -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(
                !LanguageVersion.byHearth.isScala2_13
              ), // On Scala 3 it _has_ type parameter...
              "position" -> Data("None"),
              "annotations" -> envDependentAnnotations("new native()"),
              "isConstructor" -> Data(false),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isImplicit" -> Data(false),
              "isDeclared" -> Data(false),
              "isSynthetic" -> Data(true),
              "isInherited" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(0),
              "isNullary" -> Data(true),
              "isUnary" -> Data(false),
              "isBinary" -> Data(false),
              "isConstructorArgument" -> Data(false),
              "isCaseField" -> Data(false),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(
                LanguageVersion.byHearth.isScala2_13
              ), // ...which we don't support yet, so it's false...
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(LanguageVersion.byHearth.isScala2_13), // ...and this is false...
              "isAccessor" -> Data(LanguageVersion.byHearth.isScala2_13) // ...so this is false too.
            ),
          "hashCode()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> envDependentAnnotations("new native()"),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "notify()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> envDependentAnnotations("new native()"),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "notifyAll()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> envDependentAnnotations("new native()"),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "toString()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "wait" -> Data.map(
            "()" -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(false),
              "position" -> Data("None"),
              "annotations" -> envDependentAnnotations(
                "new throws[InterruptedException](classOf[java.lang.InterruptedException])"
              ),
              "isConstructor" -> Data(false),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isImplicit" -> Data(false),
              "isDeclared" -> Data(true),
              "isSynthetic" -> Data(false),
              "isInherited" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(0),
              "isNullary" -> Data(true),
              "isUnary" -> Data(false),
              "isBinary" -> Data(false),
              "isConstructorArgument" -> Data(false),
              "isCaseField" -> Data(false),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(false),
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(false),
              "isAccessor" -> Data(false)
            ),
            "(Long)" -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(false),
              "position" -> Data("None"),
              "annotations" -> envDependentAnnotations(
                "new throws[InterruptedException](classOf[java.lang.InterruptedException])",
                "new native()"
              ),
              "isConstructor" -> Data(false),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isImplicit" -> Data(false),
              "isDeclared" -> Data(true),
              "isSynthetic" -> Data(false),
              "isInherited" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(1),
              "isNullary" -> Data(false),
              "isUnary" -> Data(true),
              "isBinary" -> Data(false),
              "isConstructorArgument" -> Data(false),
              "isCaseField" -> Data(false),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(false),
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(false),
              "isAccessor" -> Data(false)
            ),
            "(Long, Int)" -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(false),
              "position" -> Data("None"),
              "annotations" -> envDependentAnnotations(
                "new throws[InterruptedException](classOf[java.lang.InterruptedException])"
              ),
              "isConstructor" -> Data(false),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isImplicit" -> Data(false),
              "isDeclared" -> Data(true),
              "isSynthetic" -> Data(false),
              "isInherited" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(2),
              "isNullary" -> Data(false),
              "isUnary" -> Data(false),
              "isBinary" -> Data(true),
              "isConstructorArgument" -> Data(false),
              "isCaseField" -> Data(false),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(false),
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(false),
              "isAccessor" -> Data(false)
            )
          ),
          // quasi-methods generated by Scala for consistency
          "asInstanceOf" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(true),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "isInstanceOf" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(true),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "synchronized" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(true),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "==(Any)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "!=(Any)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "eq(Object)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "ne(Object)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          // null-safe hash method
          "##" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(true),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          )
        )
      }

      test("for class without companion") {
        val envDependedPosition =
          if (LanguageVersion.byHearth.isScala2_13) Data("None")
          else Data("Some(hearth-tests/src/main/scala/hearth/examples/methods.scala)")

        testMethodsExtraction[examples.methods.NoCompanionClass](
          "clone",
          "equals",
          "finalize",
          "getClass",
          "hashCode",
          "notify",
          "notifyAll",
          "toString",
          "wait",
          "asInstanceOf",
          "isInstanceOf",
          "synchronized",
          "==",
          "!=",
          "eq",
          "ne",
          "##"
        ) <==> Data.map(
          "method(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "methodWithDefault(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "methodWithAnnotation(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(Data("new hearth.examples.methods.ExampleAnnotation()")),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "methodWithAnnotatedParam(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "scalaValue" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(true),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(false),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(true),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(true),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(true)
          ),
          "scalaVariable" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(true),
            "isLazy" -> Data(false),
            "isDef" -> Data(false),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(true),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(true),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(true)
          ),
          "scalaVariable_=(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(true),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(true),
            "isScalaAccessor" -> Data(true),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(true)
          ),
          "inheritedAbstractMethod(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(true),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "inheritedFinalMethod(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> envDependedPosition,
            "annotations" -> Data.list(),
            "isConstructor" -> Data(false),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isImplicit" -> Data(false),
            "isDeclared" -> Data(false),
            "isSynthetic" -> Data(false),
            "isInherited" -> Data(true),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isConstructorArgument" -> Data(false),
            "isCaseField" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          )
        )
      }

      // TODO: class with companion

      // TODO: module
    }

    // TODO: attempt calling methods

    // TODO: attempt calling methods with default values
  }
}
