package hearth
package typed

import hearth.data.Data

/** Macro implementation is in [[MethodsFixturesImpl]] */
final class MethodsSpec extends MacroSuite {

  group("trait typed.Methods") {

    group("methods: Method.methodsOf[A], returns preprocessed methods") {
      import MethodsFixtures.testMethodsExtraction

      test(
        "for java.lang.Object".ignoreOnScala3.pending(
          "On Scala + JDK 21 we have different positions than on other JDKs or Scala 2"
        )
      ) {
        testMethodsExtraction[java.lang.Object]("getClass", "equals") <==> Data.map(
          // actual methods of java.lang.Object
          "clone()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(false),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          // Excluded because on Scala 2 it's "equals(Object)", on Scala 3 it's "equals(Any)"
          /*
            "equals(Object)" -> Data.map(
                "invocation" -> Data("OnInstance"),
                "hasTypeParameters" -> Data(false),
                "position" -> Data("None"),
                "isVal" -> Data(false),
                "isVar" -> Data(false),
                "isLazy" -> Data(false),
                "isDef" -> Data(true),
                "isInherited" -> Data(true),
                "isImplicit" -> Data(false),
                "isAvailable(Everywhere)" -> Data(true),
                "arity" -> Data(1),
                "isNullary" -> Data(false),
                "isUnary" -> Data(true),
                "isBinary" -> Data(false),
                "isScalaGetter" -> Data(false),
                "isScalaSetter" -> Data(false),
                "isScalaAccessor" -> Data(false),
                "isJavaGetter" -> Data(false),
                "isJavaSetter" -> Data(false),
                "isJavaAccessor" -> Data(false),
                "isAccessor" -> Data(false)
            ),
           */
          "finalize()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(false),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          // Excluded because on Scala 2 it's "getClass", on Scala 3 it's "getClass()"
          /*
            "getClass()" -> Data.map(
                "invocation" -> Data("OnInstance"),
                "hasTypeParameters" -> Data(false),
                "position" -> Data("None"),
                "isVal" -> Data(false),
                "isVar" -> Data(false),
                "isLazy" -> Data(false),
                "isDef" -> Data(true),
                "isInherited" -> Data(true),
                "isImplicit" -> Data(false),
                "isAvailable(Everywhere)" -> Data(true),
                "arity" -> Data(0),
                "isNullary" -> Data(true),
                "isUnary" -> Data(false),
                "isBinary" -> Data(false),
                "isScalaGetter" -> Data(false),
                "isScalaSetter" -> Data(false),
                "isScalaAccessor" -> Data(false),
                "isJavaGetter" -> Data(false),
                "isJavaSetter" -> Data(false),
                "isJavaAccessor" -> Data(false),
                "isAccessor" -> Data(false)
            ),
           */
          "hashCode()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "notify()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "notifyAll()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "toString()" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "wait" -> Data.map(
            "()" -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(false),
              "position" -> Data("None"),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isInherited" -> Data(false),
              "isImplicit" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(0),
              "isNullary" -> Data(true),
              "isUnary" -> Data(false),
              "isBinary" -> Data(false),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(false),
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(false),
              "isAccessor" -> Data(false)
            ),
            "(Long)" -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(false),
              "position" -> Data("None"),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isInherited" -> Data(false),
              "isImplicit" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(1),
              "isNullary" -> Data(false),
              "isUnary" -> Data(true),
              "isBinary" -> Data(false),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(false),
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(false),
              "isAccessor" -> Data(false)
            ),
            "(Long, Int)" -> Data.map(
              "invocation" -> Data("OnInstance"),
              "hasTypeParameters" -> Data(false),
              "position" -> Data("None"),
              "isVal" -> Data(false),
              "isVar" -> Data(false),
              "isLazy" -> Data(false),
              "isDef" -> Data(true),
              "isInherited" -> Data(false),
              "isImplicit" -> Data(false),
              "isAvailable(Everywhere)" -> Data(true),
              "arity" -> Data(2),
              "isNullary" -> Data(false),
              "isUnary" -> Data(false),
              "isBinary" -> Data(true),
              "isScalaGetter" -> Data(false),
              "isScalaSetter" -> Data(false),
              "isScalaAccessor" -> Data(false),
              "isJavaGetter" -> Data(false),
              "isJavaSetter" -> Data(false),
              "isJavaAccessor" -> Data(false),
              "isAccessor" -> Data(false)
            )
          ),
          // quasi-methods generated by Scala for consistency
          "asInstanceOf" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(true),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(true),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "isInstanceOf" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(true),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(true),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "synchronized" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(true),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "==(Any)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "!=(Any)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "eq(Object)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "ne(Object)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          // null-safe hash method
          "##" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("None"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          )
        )
      }

      test("for class without companion".ignore.pending("We need to fix recognition of val/var/Scala getter/setter")) {
        testMethodsExtraction[examples.methods.NoCompanionClass](
          "clone",
          "equals",
          "finalize",
          "getClass",
          "hashCode",
          "notify",
          "notifyAll",
          "toString",
          "wait",
          "asInstanceOf",
          "isInstanceOf",
          "synchronized",
          "==",
          "!=",
          "eq",
          "ne",
          "##"
        ) <==> Data.map(
          "method(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "methodWithDefault(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "methodWithAnnotation(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "methodWithAnnotatedParam(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "scalaValue" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(true),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(false),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(true),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(true),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(true)
          ),
          "scalaVariable" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(true),
            "isLazy" -> Data(false),
            "isDef" -> Data(false),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(0),
            "isNullary" -> Data(true),
            "isUnary" -> Data(false),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(true),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(true),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(true)
          ),
          "scalaVariable_=(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(true),
            "isLazy" -> Data(false),
            "isDef" -> Data(false),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(true),
            "isScalaAccessor" -> Data(true),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(true)
          ),
          "inheritedAbstractMethod(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(false),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          ),
          "inheritedFinalMethod(Int)" -> Data.map(
            "invocation" -> Data("OnInstance"),
            "hasTypeParameters" -> Data(false),
            "position" -> Data("Some(hearth-tests/src/test/scala/hearth/examples/methods.scala)"),
            "isVal" -> Data(false),
            "isVar" -> Data(false),
            "isLazy" -> Data(false),
            "isDef" -> Data(true),
            "isInherited" -> Data(true),
            "isImplicit" -> Data(false),
            "isAvailable(Everywhere)" -> Data(true),
            "arity" -> Data(1),
            "isNullary" -> Data(false),
            "isUnary" -> Data(true),
            "isBinary" -> Data(false),
            "isScalaGetter" -> Data(false),
            "isScalaSetter" -> Data(false),
            "isScalaAccessor" -> Data(false),
            "isJavaGetter" -> Data(false),
            "isJavaSetter" -> Data(false),
            "isJavaAccessor" -> Data(false),
            "isAccessor" -> Data(false)
          )
        )
      }
    }
  }
}
