build:
  docker build . -t mkdocs-hearth-docs

serve: build
  docker run --rm -it -p 8000:8000 -v ${PWD}:/docs --env "CI_LATEST_TAG=$(git describe --tags)" mkdocs-hearth-docs

test-snippets:
  cd .. && sbt --client "publish-local-for-tests"
  cd .. && scala-cli run scripts/test-snippets.scala -- --extra "hearth-version=$(sbt -batch -error 'print hearth/version' 2>/dev/null | grep -oE '^[0-9][^ \[]*')" "$PWD/docs/user-guide"
